-- POLSKIFY 3.0 — SPECIAL QUIZZES / ADMIN 2.0 / SEASONS
-- Run in Supabase SQL Editor after previous Polskify patches.

alter table public.profiles add column if not exists banned boolean not null default false;

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  starts_at date not null,
  ends_at date not null,
  active boolean not null default true
);

create table if not exists public.season_entries (
  season_id bigint not null references public.seasons(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  points integer not null default 0,
  primary key(season_id,user_id)
);

alter table public.seasons enable row level security;
alter table public.season_entries enable row level security;
grant select on public.seasons, public.season_entries to authenticated;
drop policy if exists "seasons_read" on public.seasons;
create policy "seasons_read" on public.seasons for select to authenticated using(true);
drop policy if exists "season_entries_read" on public.season_entries;
create policy "season_entries_read" on public.season_entries for select to authenticated using(true);

insert into public.seasons(name,starts_at,ends_at,active)
select
  'Sezon ' || to_char(current_date,'MM/YYYY'),
  date_trunc('month',current_date)::date,
  (date_trunc('month',current_date)+interval '1 month - 1 day')::date,
  true
where not exists (
  select 1 from public.seasons
  where current_date between starts_at and ends_at
);

create or replace function public.award_special_quiz_xp(
  p_quiz_code text,
  p_score integer,
  p_total integer
)
returns table(
  xp_awarded integer,
  total_xp integer,
  weekly_xp integer,
  league text,
  week_key date,
  region_passed boolean,
  already_rewarded boolean
)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_reward integer;
  v_week date:=current_date-((extract(isodow from current_date)::int)-1);
  v_exists boolean;
  v_league text;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_quiz_code not in ('SPECIAL_RANDOM','SPECIAL_CAPITALS','SPECIAL_RIVERS','SPECIAL_NEIGHBORS','SPECIAL_FLAGS','SPECIAL_LANDMARKS') then
    raise exception 'Invalid quiz';
  end if;
  if p_total<>10 or p_score<0 or p_score>10 then raise exception 'Invalid result'; end if;

  insert into public.progress(user_id) values(v_uid) on conflict(user_id) do nothing;
  select exists(select 1 from public.quiz_rewards where user_id=v_uid and region_code=p_quiz_code and reward_day=current_date) into v_exists;

  if v_exists then
    select p.xp,p.weekly_xp,p.league,p.week_key into total_xp,weekly_xp,league,week_key
    from public.progress p where p.user_id=v_uid;
    xp_awarded:=0; region_passed:=false; already_rewarded:=true; return next; return;
  end if;

  v_reward:=(p_score*10)+case when p_score>=5 then 20 else 0 end;

  update public.progress p
  set xp=p.xp+v_reward,
      weekly_xp=case when p.week_key is distinct from v_week then v_reward else p.weekly_xp+v_reward end,
      week_key=v_week,
      updated_at=now()
  where p.user_id=v_uid;

  update public.progress p set league=case when weekly_xp>=1200 then 'gold' when weekly_xp>=500 then 'silver' else 'bronze' end
  where p.user_id=v_uid;

  insert into public.quiz_rewards(user_id,region_code,reward_day,score,xp_awarded)
  values(v_uid,p_quiz_code,current_date,p_score,v_reward);

  select p.xp,p.weekly_xp,p.league,p.week_key into total_xp,weekly_xp,league,week_key
  from public.progress p where p.user_id=v_uid;

  insert into public.league_entries(user_id,display_name,weekly_xp,league,week_key,updated_at)
  select v_uid,coalesce(pr.display_name,split_part(u.email,'@',1),'gracz'),weekly_xp,league,week_key,now()
  from auth.users u left join public.profiles pr on pr.id=u.id where u.id=v_uid
  on conflict(user_id) do update set weekly_xp=excluded.weekly_xp,league=excluded.league,week_key=excluded.week_key,updated_at=now();

  xp_awarded:=v_reward; region_passed:=false; already_rewarded:=false; return next;
end;
$$;
revoke all on function public.award_special_quiz_xp(text,integer,integer) from public,anon;
grant execute on function public.award_special_quiz_xp(text,integer,integer) to authenticated;

create or replace function public.get_current_season()
returns table(name text, ends_at date, points integer)
language plpgsql security definer set search_path=public
as $$
declare v_uid uuid:=auth.uid(); v_sid bigint;
begin
  select id,s.name,s.ends_at into v_sid,name,ends_at from public.seasons s
  where current_date between s.starts_at and s.ends_at order by s.id desc limit 1;
  if v_sid is null then return; end if;
  select coalesce(se.points,0) into points from public.season_entries se where se.season_id=v_sid and se.user_id=v_uid;
  points:=coalesce(points,0); return next;
end; $$;
grant execute on function public.get_current_season() to authenticated;

create or replace function public.quiz_reward_to_season()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_sid bigint;
begin
  select id into v_sid from public.seasons where new.reward_day between starts_at and ends_at order by id desc limit 1;
  if v_sid is not null then
    insert into public.season_entries(season_id,user_id,points) values(v_sid,new.user_id,new.xp_awarded)
    on conflict(season_id,user_id) do update set points=public.season_entries.points+excluded.points;
  end if;
  return new;
end; $$;
drop trigger if exists trg_quiz_reward_season on public.quiz_rewards;
create trigger trg_quiz_reward_season after insert on public.quiz_rewards for each row execute function public.quiz_reward_to_season();

create or replace function public.admin_list_users()
returns table(user_id uuid,email text,xp integer,streak_count integer,banned boolean)
language plpgsql security definer set search_path=public as $$
declare v_admin boolean;
begin
  select is_admin into v_admin from public.profiles where id=auth.uid();
  if coalesce(v_admin,false)=false then raise exception 'Admin only'; end if;
  return query
  select u.id,u.email,coalesce(p.xp,0),coalesce(p.streak_count,0),coalesce(pr.banned,false)
  from auth.users u
  left join public.progress p on p.user_id=u.id
  left join public.profiles pr on pr.id=u.id
  order by u.created_at desc limit 200;
end; $$;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.admin_user_action(p_user_id uuid,p_action text,p_value text default null)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_admin boolean;
begin
  select is_admin into v_admin from public.profiles where id=auth.uid();
  if coalesce(v_admin,false)=false then raise exception 'Admin only'; end if;

  if p_action='ban' then update public.profiles set banned=true where id=p_user_id;
  elsif p_action='unban' then update public.profiles set banned=false where id=p_user_id;
  elsif p_action='resetstreak' then update public.progress set streak_count=0,streak_last_day=null where user_id=p_user_id;
  elsif p_action='setxp' then update public.progress set xp=greatest(0,coalesce(p_value,'0')::integer) where user_id=p_user_id;
  else raise exception 'Unknown action';
  end if;
  return true;
end; $$;
grant execute on function public.admin_user_action(uuid,text,text) to authenticated;


-- ===== ANTICHEAT 2.0 =====
create extension if not exists pgcrypto;
create table if not exists public.quiz_questions(
 id text primary key, quiz_code text not null, question text not null,
 options jsonb not null, correct_index integer not null check(correct_index between 0 and 3)
);
create table if not exists public.quiz_sessions(
 id uuid primary key default gen_random_uuid(),
 user_id uuid not null references auth.users(id) on delete cascade,
 quiz_code text not null, question_ids jsonb not null,
 answers jsonb not null default '{}'::jsonb,
 completed boolean not null default false, created_at timestamptz not null default now()
);
alter table public.quiz_questions enable row level security;
alter table public.quiz_sessions enable row level security;
revoke all on public.quiz_questions,public.quiz_sessions from anon,authenticated;

insert into public.quiz_questions(id,quiz_code,question,options,correct_index) values
('ZP_01','ZP','Jakie miasto jest stolicą województwa zachodniopomorskiego?','["Szczecin", "Koszalin", "Świnoujście", "Stargard"]'::jsonb,0),
('ZP_02','ZP','Z którym morzem graniczy województwo zachodniopomorskie?','["Bałtyckim", "Północnym", "Śródziemnym", "Czarnym"]'::jsonb,0),
('ZP_03','ZP','Który park narodowy leży w województwie zachodniopomorskim?','["Woliński Park Narodowy", "Ojcowski Park Narodowy", "Biebrzański Park Narodowy", "Tatrzański Park Narodowy"]'::jsonb,0),
('ZP_04','ZP','Jaka rzeka tworzy dużą część zachodniej granicy województwa?','["Odra", "Wisła", "Warta", "San"]'::jsonb,0),
('ZP_05','ZP','Które miasto leży na wyspie Wolin?','["Świnoujście", "Koszalin", "Wałcz", "Gryfice"]'::jsonb,0),
('ZP_06','ZP','Jak nazywa się znana nadmorska miejscowość uzdrowiskowa z molem?','["Kołobrzeg", "Szczecinek", "Myślibórz", "Choszczno"]'::jsonb,0),
('ZP_07','ZP','Jaki duży akwen znajduje się na północ od Szczecina?','["Zalew Szczeciński", "Jezioro Śniardwy", "Zalew Zegrzyński", "Zalew Wiślany"]'::jsonb,0),
('ZP_08','ZP','Która wyspa jest kojarzona z Międzyzdrojami?','["Wolin", "Wielkanocna", "Sobieszewska", "Słodowa"]'::jsonb,0),
('ZP_09','ZP','Co znajduje się w Szczecinie i jest ważnym zabytkiem miasta?','["Zamek Książąt Pomorskich", "Wawel", "Zamek Królewski na Wawelu", "Zamek w Malborku"]'::jsonb,0),
('ZP_10','ZP','Jaki typ krajobrazu jest charakterystyczny dla północnej części województwa?','["Nadmorski", "Wysokogórski", "Pustynny", "Tundrowy"]'::jsonb,0),
('PM_01','PM','Jakie miasto jest stolicą województwa pomorskiego?','["Gdańsk", "Gdynia", "Sopot", "Bytów"]'::jsonb,0),
('PM_02','PM','Z jakim morzem graniczy województwo pomorskie?','["Bałtyckim", "Czarnym", "Północnym", "Adriatyckim"]'::jsonb,0),
('PM_03','PM','Jak nazywa się charakterystyczny półwysep wysunięty w Zatokę Pucką?','["Półwysep Helski", "Półwysep Jutlandzki", "Mierzeja Wiślana", "Wyspa Wolin"]'::jsonb,0),
('PM_04','PM','Przez Gdańsk przepływa rzeka:','["Motława", "Narew", "San", "Pilica"]'::jsonb,0),
('PM_05','PM','Które miasto razem z Gdańskiem i Gdynią tworzy Trójmiasto?','["Sopot", "Malbork", "Tczew", "Wejherowo"]'::jsonb,0),
('PM_06','PM','Jak nazywa się region kulturowy znany z własnej tradycji i języka?','["Kaszuby", "Kurpie", "Podhale", "Roztocze"]'::jsonb,0),
('PM_07','PM','Który zabytek kojarzy się z Gdańskiem?','["Żuraw", "Spodek", "Hala Stulecia", "Pałac Kultury"]'::jsonb,0),
('PM_08','PM','W którym mieście znajduje się port i słynne Muzeum Emigracji?','["Gdynia", "Sopot", "Malbork", "Słupsk"]'::jsonb,0),
('PM_09','PM','Jak nazywa się największy zamek krzyżacki w Malborku?','["Zamek w Malborku", "Zamek Książ", "Zamek Ogrodzieniec", "Zamek Czocha"]'::jsonb,0),
('PM_10','PM','Który park narodowy leży na wybrzeżu województwa?','["Słowiński Park Narodowy", "Biebrzański Park Narodowy", "Ojcowski Park Narodowy", "Tatrzański Park Narodowy"]'::jsonb,0),
('WN_01','WN','Jakie miasto jest stolicą województwa warmińsko-mazurskiego?','["Olsztyn", "Elbląg", "Ełk", "Iława"]'::jsonb,0),
('WN_02','WN','Z czego najbardziej znane są Mazury?','["Z licznych jezior", "Z wysokich gór", "Z pustyń", "Z klifów nad Atlantykiem"]'::jsonb,0),
('WN_03','WN','Które jezioro jest największym jeziorem w Polsce?','["Śniardwy", "Mamry", "Hańcza", "Jeziorak"]'::jsonb,0),
('WN_04','WN','W którym mieście znajduje się planetarium i obserwatorium związane z Mikołajem Kopernikiem?','["Frombork", "Malbork", "Nidzica", "Mrągowo"]'::jsonb,0),
('WN_05','WN','Który kanał łączy jeziora i jest jedną z atrakcji regionu?','["Kanał Elbląski", "Kanał Augustowski", "Kanał Gliwicki", "Kanał Żerański"]'::jsonb,0),
('WN_06','WN','Które zwierzę jest symbolem Mazurskiego Parku Krajobrazowego?','["Bocian czarny", "Pingwin", "Koala", "Renifer"]'::jsonb,0),
('WN_07','WN','Które miasto leży nad jeziorem Niegocin?','["Giżycko", "Olsztyn", "Elbląg", "Braniewo"]'::jsonb,0),
('WN_08','WN','Jak nazywa się kraina historyczna związana z Olsztynem?','["Warmia", "Podlasie", "Kaszuby", "Mazowsze"]'::jsonb,0),
('WN_09','WN','Które jezioro jest jednym z największych w Polsce i leży na Mazurach?','["Mamry", "Morskie Oko", "Jezioro Żywieckie", "Gopło"]'::jsonb,0),
('WN_10','WN','Jaki sport wodny jest szczególnie popularny na Mazurach?','["Żeglarstwo", "Narciarstwo alpejskie", "Surfing na oceanie", "Hokej na lodzie"]'::jsonb,0),
('PD_01','PD','Jakie miasto jest stolicą województwa podlaskiego?','["Białystok", "Łomża", "Suwałki", "Augustów"]'::jsonb,0),
('PD_02','PD','Który park narodowy chroni część Puszczy Białowieskiej?','["Białowieski Park Narodowy", "Słowiński Park Narodowy", "Kampinoski Park Narodowy", "Wigierski Park Narodowy"]'::jsonb,0),
('PD_03','PD','Która rzeka jest jednym z najważniejszych cieków Podlasia?','["Narew", "Warta", "Odra", "Dunajec"]'::jsonb,0),
('PD_04','PD','Z którym państwem Polska graniczy w województwie podlaskim?','["Białorusią", "Czechami", "Słowacją", "Niemcami"]'::jsonb,0),
('PD_05','PD','Jakie zwierzę szczególnie kojarzy się z Puszczą Białowieską?','["Żubr", "Lew", "Kangur", "Wielbłąd"]'::jsonb,0),
('PD_06','PD','Które miasto słynie z kanału łączącego dorzecza Wisły i Niemna?','["Augustów", "Białystok", "Łomża", "Hajnówka"]'::jsonb,0),
('PD_07','PD','Który park narodowy chroni rozlewiska rzeki Biebrzy?','["Biebrzański Park Narodowy", "Ojcowski Park Narodowy", "Karkonoski Park Narodowy", "Woliński Park Narodowy"]'::jsonb,0),
('PD_08','PD','Jak nazywa się mniejszość, z którą kojarzy się część okolic Hajnówki?','["Białoruska", "Duńska", "Hiszpańska", "Portugalska"]'::jsonb,0),
('PD_09','PD','Który z tych parków narodowych leży w Podlaskiem?','["Wigierski Park Narodowy", "Tatrzański Park Narodowy", "Bieszczadzki Park Narodowy", "Kampinoski Park Narodowy"]'::jsonb,0),
('PD_10','PD','Jakie miasto jest jednym z ważnych ośrodków przemysłu i kultury regionu?','["Białystok", "Gdynia", "Opole", "Wałbrzych"]'::jsonb,0),
('LB_01','LB','Jakie dwa miasta są siedzibami władz województwa lubuskiego?','["Gorzów Wielkopolski i Zielona Góra", "Poznań i Kalisz", "Wrocław i Opole", "Bydgoszcz i Toruń"]'::jsonb,0),
('LB_02','LB','Która duża rzeka przepływa przez województwo lubuskie?','["Odra", "San", "Narew", "Dunajec"]'::jsonb,0),
('LB_03','LB','Który park krajobrazowy i obiekt UNESCO słynie z ogromnego parku położonego przy granicy z Niemcami?','["Park Mużakowski", "Park Śląski", "Park Gródek", "Park Zdrojowy"]'::jsonb,0),
('LB_04','LB','Województwo lubuskie leży w zachodniej części Polski przy granicy z:','["Niemcami", "Ukrainą", "Litwą", "Czechami"]'::jsonb,0),
('LB_05','LB','Które miasto słynie z tradycji winiarskich?','["Zielona Góra", "Gorzów Wielkopolski", "Słubice", "Żagań"]'::jsonb,0),
('LB_06','LB','Który park narodowy leży w województwie lubuskim?','["Park Narodowy Ujście Warty", "Białowieski Park Narodowy", "Ojcowski Park Narodowy", "Tatrzański Park Narodowy"]'::jsonb,0),
('LB_07','LB','Który z tych mostów przekracza Odrę na granicy Polski i Niemiec?','["Most w Słubicach i Frankfurcie nad Odrą", "Most Świętokrzyski", "Most Grunwaldzki", "Most Dębnicki"]'::jsonb,0),
('LB_08','LB','Jakie miasto słynie z zamku i dawnej twierdzy?','["Kostrzyn nad Odrą", "Sopot", "Puck", "Zakopane"]'::jsonb,0),
('LB_09','LB','Które miasto jest stolicą województwa lubuskiego wspólnie z Gorzowem Wielkopolskim jako siedzibą władz?','["Zielona Góra", "Słubice", "Żagań", "Nowa Sól"]'::jsonb,0),
('LB_10','LB','Co jest charakterystyczne dla krajobrazu województwa lubuskiego?','["Duża liczba lasów i jezior", "Lodowce", "Wysokie Tatry", "Pustynie"]'::jsonb,0),
('KP_01','KP','Które dwa miasta są siedzibami władz województwa kujawsko-pomorskiego?','["Bydgoszcz i Toruń", "Włocławek i Grudziądz", "Toruń i Inowrocław", "Bydgoszcz i Płock"]'::jsonb,0),
('KP_02','KP','Z którego miasta pochodził Mikołaj Kopernik?','["Toruń", "Bydgoszcz", "Chełmno", "Włocławek"]'::jsonb,0),
('KP_03','KP','Która wielka rzeka przepływa przez Toruń?','["Wisła", "Odra", "Warta", "Bug"]'::jsonb,0),
('KP_04','KP','Toruń słynie między innymi z:','["Pierników", "Oscypków", "Krupnioków", "Obwarzanków"]'::jsonb,0),
('KP_05','KP','Jak nazywa się duży kanał wodny w Bydgoszczy łączący dorzecza?','["Kanał Bydgoski", "Kanał Elbląski", "Kanał Augustowski", "Kanał Gliwicki"]'::jsonb,0),
('KP_06','KP','Które miasto słynie z tężni solankowych?','["Ciechocinek", "Chełmno", "Toruń", "Brodnica"]'::jsonb,0),
('KP_07','KP','Który park narodowy leży w województwie kujawsko-pomorskim?','["Brak parku narodowego", "Wielkopolski Park Narodowy", "Biebrzański Park Narodowy", "Woliński Park Narodowy"]'::jsonb,0),
('KP_08','KP','Jak nazywa się zabytkowe miasto słynące z gotyckiej architektury nad Wisłą?','["Toruń", "Zakopane", "Szczecin", "Lublin"]'::jsonb,0),
('KP_09','KP','Który rodzaj soli kojarzy się z Ciechocinkiem?','["Solanka", "Sól morska z oceanu", "Sól kamienna z Sahary", "Sól himalajska"]'::jsonb,0),
('KP_10','KP','Jaką rzeką jest Brda, która przepływa przez Bydgoszcz?','["Dopływem Wisły", "Dopływem Odry", "Dopływem Bugu", "Dopływem Sanu"]'::jsonb,0),
('WP_01','WP','Jakie miasto jest stolicą województwa wielkopolskiego?','["Poznań", "Kalisz", "Leszno", "Gniezno"]'::jsonb,0),
('WP_02','WP','Jaka rzeka przepływa przez Poznań?','["Warta", "Wisła", "Odra", "Bug"]'::jsonb,0),
('WP_03','WP','W którym mieście znajduje się słynna katedra związana z początkami państwa polskiego?','["Gniezno", "Konin", "Piła", "Ostrów Wielkopolski"]'::jsonb,0),
('WP_04','WP','Który park narodowy leży w województwie wielkopolskim?','["Wielkopolski Park Narodowy", "Białowieski Park Narodowy", "Tatrzański Park Narodowy", "Roztoczański Park Narodowy"]'::jsonb,0),
('WP_05','WP','Co według tradycji znajduje się na poznańskim Starym Rynku?','["Koziołki", "Żurawie", "Smoki wawelskie", "Syrenka"]'::jsonb,0),
('WP_06','WP','Jak nazywa się słynna poznańska bułka z nadzieniem z białego maku?','["Rogal świętomarciński", "Obwarzanek krakowski", "Krupniok", "Kołacz"]'::jsonb,0),
('WP_07','WP','Które jezioro jest jednym z największych w Wielkopolsce?','["Powidzkie", "Morskie Oko", "Hańcza", "Śniardwy"]'::jsonb,0),
('WP_08','WP','Jak nazywa się historyczna kraina związana z Gnieznem i Poznaniem?','["Wielkopolska", "Małopolska", "Warmia", "Kaszuby"]'::jsonb,0),
('WP_09','WP','Które miasto jest ważnym ośrodkiem przemysłowym i kulturalnym na południu regionu?','["Kalisz", "Hel", "Białystok", "Olsztyn"]'::jsonb,0),
('WP_10','WP','Jaki ptak pojawia się w legendzie o początkach państwa polskiego?','["Orzeł biały", "Pingwin", "Flaming", "Pelikan"]'::jsonb,0),
('MZ_01','MZ','Jakie miasto jest stolicą województwa mazowieckiego?','["Warszawa", "Radom", "Płock", "Siedlce"]'::jsonb,0),
('MZ_02','MZ','Przez Warszawę przepływa rzeka:','["Wisła", "Odra", "Warta", "Narew"]'::jsonb,0),
('MZ_03','MZ','Który park narodowy leży niedaleko Warszawy?','["Kampinoski Park Narodowy", "Wigierski Park Narodowy", "Bieszczadzki Park Narodowy", "Ojcowski Park Narodowy"]'::jsonb,0),
('MZ_04','MZ','Mazowieckie leży głównie w:','["środkowo-wschodniej Polsce", "północno-zachodniej Polsce", "południowo-zachodniej Polsce", "wyłącznie nad Bałtykiem"]'::jsonb,0),
('MZ_05','MZ','Które miasto słynie z Pałacu Kultury i Nauki?','["Warszawa", "Płock", "Radom", "Siedlce"]'::jsonb,0),
('MZ_06','MZ','Jak nazywa się historyczny zespół staromiejski Warszawy?','["Stare Miasto", "Kazimierz", "Nikiszowiec", "Ostrów Tumski"]'::jsonb,0),
('MZ_07','MZ','Która rzeka jest dużym dopływem Wisły i płynie przez północną część regionu?','["Narew", "San", "Noteć", "Odra"]'::jsonb,0),
('MZ_08','MZ','Z jakim kompozytorem szczególnie kojarzy się Żelazowa Wola?','["Fryderyk Chopin", "Stanisław Moniuszko", "Henryk Wieniawski", "Ignacy Jan Paderewski"]'::jsonb,0),
('MZ_09','MZ','Które miasto leży nad Wisłą i jest jednym z najstarszych ośrodków Mazowsza?','["Płock", "Sopot", "Kołobrzeg", "Krosno"]'::jsonb,0),
('MZ_10','MZ','Jak nazywa się duży kompleks leśny wokół Warszawy objęty ochroną?','["Puszcza Kampinoska", "Puszcza Białowieska", "Puszcza Notecka", "Puszcza Niepołomicka"]'::jsonb,0),
('LD_01','LD','Jakie miasto jest stolicą województwa łódzkiego?','["Łódź", "Piotrków Trybunalski", "Skierniewice", "Pabianice"]'::jsonb,0),
('LD_02','LD','Łódź była historycznie bardzo ważnym ośrodkiem:','["przemysłu włókienniczego", "rybołówstwa morskiego", "wydobycia ropy naftowej", "stoczniowym"]'::jsonb,0),
('LD_03','LD','Najbardziej znaną ulicą reprezentacyjną Łodzi jest:','["Piotrkowska", "Długa", "Floriańska", "Mariacka"]'::jsonb,0),
('LD_04','LD','Województwo łódzkie leży mniej więcej w:','["centrum Polski", "skrajnym północnym zachodzie", "górach", "północno-wschodnim narożniku"]'::jsonb,0),
('LD_05','LD','Jak nazywa się słynny kompleks fabryczny i centrum kultury w Łodzi?','["Manufaktura", "Stocznia", "Spodek", "Nikiszowiec"]'::jsonb,0),
('LD_06','LD','Która rzeka jest dopływem Wisły i płynie przez część województwa?','["Pilica", "Odra", "Warta", "San"]'::jsonb,0),
('LD_07','LD','Które miasto słynie z długiej ulicy Piotrkowskiej?','["Łódź", "Zgierz", "Łowicz", "Kutno"]'::jsonb,0),
('LD_08','LD','Jak nazywa się ważny ośrodek przemysłowy na południu regionu?','["Piotrków Trybunalski", "Hel", "Sopot", "Ełk"]'::jsonb,0),
('LD_09','LD','Która miejscowość kojarzy się z tradycją ludową i charakterystycznymi pasiakami?','["Łowicz", "Pabianice", "Bełchatów", "Łęczyca"]'::jsonb,0),
('LD_10','LD','Jak nazywa się główna rzeka przepływająca przez Łódź?','["Nie ma jednej dużej rzeki przepływającej przez centrum; przez miasto płyną mniejsze rzeki", "Wisła", "Odra", "Bug"]'::jsonb,0),
('LU_01','LU','Jakie miasto jest stolicą województwa lubelskiego?','["Lublin", "Zamość", "Chełm", "Biała Podlaska"]'::jsonb,0),
('LU_02','LU','Która miejscowość słynie z malowniczego położenia nad Wisłą i zabytkowego rynku?','["Kazimierz Dolny", "Nałęczów", "Biłgoraj", "Łuków"]'::jsonb,0),
('LU_03','LU','Wschodnią granicę województwa lubelskiego tworzy między innymi rzeka:','["Bug", "Odra", "Warta", "Nida"]'::jsonb,0),
('LU_04','LU','Na południu województwa znajduje się kraina geograficzna:','["Roztocze", "Kaszyby", "Puszcza Notecka", "Żuławy"]'::jsonb,0),
('LU_05','LU','Które miasto jest znane z renesansowej zabudowy i wpisanego na listę UNESCO Starego Miasta?','["Zamość", "Puławy", "Chełm", "Biała Podlaska"]'::jsonb,0),
('LU_06','LU','Który park narodowy leży w Lubelskiem?','["Poleski Park Narodowy", "Tatrzański Park Narodowy", "Wigierski Park Narodowy", "Woliński Park Narodowy"]'::jsonb,0),
('LU_07','LU','Jaka rzeka przepływa przez Lublin?','["Bystrzyca", "Wisła", "Odra", "San"]'::jsonb,0),
('LU_08','LU','Które miasto jest ważnym ośrodkiem akademickim regionu?','["Lublin", "Hel", "Zakopane", "Tarnów"]'::jsonb,0),
('LU_09','LU','Jak nazywa się kraina historyczna obejmująca wschodnią część Polski z Chełmem?','["Chełmszczyzna", "Kaszuby", "Śląsk Cieszyński", "Spisz"]'::jsonb,0),
('LU_10','LU','Który z produktów jest silnie kojarzony z Roztoczem i Lubelszczyzną?','["Uprawa chmielu", "Plantacje bananów", "Hodowla wielbłądów", "Uprawa kawy"]'::jsonb,0),
('DS_01','DS','Jakie miasto jest stolicą województwa dolnośląskiego?','["Wrocław", "Legnica", "Wałbrzych", "Jelenia Góra"]'::jsonb,0),
('DS_02','DS','Przez Wrocław przepływa rzeka:','["Odra", "Wisła", "Warta", "San"]'::jsonb,0),
('DS_03','DS','Które pasmo górskie znajduje się w południowej części województwa?','["Sudety", "Tatry", "Beskid Niski", "Bieszczady"]'::jsonb,0),
('DS_04','DS','Zamek Książ znajduje się w pobliżu:','["Wałbrzycha", "Wrocławia", "Legnicy", "Lubina"]'::jsonb,0),
('DS_05','DS','Jak nazywa się najwyższy szczyt Sudetów?','["Śnieżka", "Rysy", "Tarnica", "Łysica"]'::jsonb,0),
('DS_06','DS','Które miasto słynie z krasnali na ulicach?','["Wrocław", "Legnica", "Jelenia Góra", "Lubin"]'::jsonb,0),
('DS_07','DS','Który park narodowy leży na Dolnym Śląsku?','["Karkonoski Park Narodowy", "Biebrzański Park Narodowy", "Woliński Park Narodowy", "Roztoczański Park Narodowy"]'::jsonb,0),
('DS_08','DS','Jak nazywa się słynna hala z 1913 roku wpisana na listę UNESCO?','["Hala Stulecia", "Spodek", "Hala Olivia", "Ergo Arena"]'::jsonb,0),
('DS_09','DS','Które miasto jest znanym uzdrowiskiem u podnóża Sudetów?','["Kudowa-Zdrój", "Sopot", "Słupsk", "Giżycko"]'::jsonb,0),
('DS_10','DS','Jaki przemysł jest historycznie ważny dla okolic Wałbrzycha?','["Górnictwo", "Rybołówstwo dalekomorskie", "Stoczniowy", "Wielorybnictwo"]'::jsonb,0),
('OP_01','OP','Jakie miasto jest stolicą województwa opolskiego?','["Opole", "Nysa", "Brzeg", "Kędzierzyn-Koźle"]'::jsonb,0),
('OP_02','OP','Która rzeka przepływa przez Opole?','["Odra", "Wisła", "Narew", "Bug"]'::jsonb,0),
('OP_03','OP','Która znana miejscowość słynie z bazyliki i góry będącej miejscem ważnych wydarzeń historycznych?','["Góra Świętej Anny", "Paczków", "Otmuchów", "Brzeg"]'::jsonb,0),
('OP_04','OP','Województwo opolskie jest położone w:','["południowo-zachodniej Polsce", "północno-wschodniej Polsce", "środkowej Polsce", "wyłącznie nad Bałtykiem"]'::jsonb,0),
('OP_05','OP','Z czego słynie Opole jako miasto?','["Z festiwalu polskiej piosenki", "Z żeglarskich regat oceanicznych", "Z kopalni soli", "Z zamku krzyżackiego"]'::jsonb,0),
('OP_06','OP','Które miasto słynie z dobrze zachowanych murów obronnych?','["Paczków", "Hel", "Sopot", "Ełk"]'::jsonb,0),
('OP_07','OP','Jak nazywa się duży zamek położony nad Odrą w Brzegu?','["Zamek Piastów Śląskich", "Zamek Książ", "Zamek w Malborku", "Zamek Ogrodzieniec"]'::jsonb,0),
('OP_08','OP','Które jezioro jest znane w okolicach Nysy?','["Jezioro Nyskie", "Jezioro Hańcza", "Śniardwy", "Jeziorak"]'::jsonb,0),
('OP_09','OP','Jaki kolor często kojarzy się z barwami Opola?','["Niebieski i biały", "Czarny i zielony", "Żółty i fioletowy", "Czerwony i czarny"]'::jsonb,0),
('OP_10','OP','Która z tych gałęzi przemysłu ma duże znaczenie w regionie?','["Przemysł chemiczny", "Wielorybnictwo", "Wydobycie diamentów", "Przemysł kosmiczny na pustyni"]'::jsonb,0),
('SK_01','SK','Jakie miasto jest stolicą województwa świętokrzyskiego?','["Kielce", "Ostrowiec Świętokrzyski", "Sandomierz", "Starachowice"]'::jsonb,0),
('SK_02','SK','Jak nazywają się stare góry znajdujące się w regionie?','["Góry Świętokrzyskie", "Sudety", "Tatry", "Beskid Sądecki"]'::jsonb,0),
('SK_03','SK','Na której górze znajduje się słynne sanktuarium na Świętym Krzyżu?','["Łysej Górze", "Śnieżce", "Giewoncie", "Tarnicy"]'::jsonb,0),
('SK_04','SK','Jaskinia Raj znajduje się w pobliżu:','["Kielc", "Sandomierza", "Buska-Zdroju", "Końskich"]'::jsonb,0),
('SK_05','SK','Jak nazywają się charakterystyczne rumowiska skalne w Górach Świętokrzyskich?','["Gołoborza", "Morena", "Klify", "Wydmy"]'::jsonb,0),
('SK_06','SK','Które miasto słynie z malowniczego rynku i położenia nad Wisłą?','["Sandomierz", "Kielce", "Skarżysko-Kamienna", "Starachowice"]'::jsonb,0),
('SK_07','SK','Który park narodowy leży w województwie świętokrzyskim?','["Świętokrzyski Park Narodowy", "Białowieski Park Narodowy", "Woliński Park Narodowy", "Słowiński Park Narodowy"]'::jsonb,0),
('SK_08','SK','Jakie pasmo jest jednym z najstarszych w Polsce?','["Góry Świętokrzyskie", "Tatry", "Pieniny", "Beskid Żywiecki"]'::jsonb,0),
('SK_09','SK','Które miasto jest ważnym ośrodkiem targowym regionu?','["Kielce", "Hel", "Gdynia", "Suwałki"]'::jsonb,0),
('SK_10','SK','Jaki surowiec wydobywano historycznie w wielu miejscach regionu?','["Rudy metali", "Ropę z morza", "Diamenty", "Węgiel kamienny wyłącznie spod Bałtyku"]'::jsonb,0),
('SL_01','SL','Jakie miasto jest stolicą województwa śląskiego?','["Katowice", "Gliwice", "Częstochowa", "Bielsko-Biała"]'::jsonb,0),
('SL_02','SL','Katowicki Spodek jest przede wszystkim:','["halą widowiskowo-sportową", "zamkiem", "kopalnią", "planetarium"]'::jsonb,0),
('SL_03','SL','Z czego historycznie słynęła przemysłowa część Górnego Śląska?','["Górnictwa i hutnictwa", "Uprawy winorośli", "Rybołówstwa morskiego", "Hodowli reniferów"]'::jsonb,0),
('SL_04','SL','W którym mieście znajduje się zabytkowe osiedle Nikiszowiec?','["Katowicach", "Tychach", "Rybniku", "Sosnowcu"]'::jsonb,0),
('SL_05','SL','Które góry znajdują się na południu województwa?','["Beskidy", "Tatry", "Bieszczady", "Góry Świętokrzyskie"]'::jsonb,0),
('SL_06','SL','Z jakiego miasta słynie Jasna Góra?','["Częstochowa", "Gliwice", "Ruda Śląska", "Żory"]'::jsonb,0),
('SL_07','SL','Która kraina geograficzna obejmuje północną część województwa?','["Jura Krakowsko-Częstochowska", "Pojezierze Mazurskie", "Roztocze", "Żuławy"]'::jsonb,0),
('SL_08','SL','Jak nazywa się park położony między Chorzowem a Katowicami?','["Park Śląski", "Park Mużakowski", "Park Saski", "Park Cytadela"]'::jsonb,0),
('SL_09','SL','Które miasto jest znane z zabytkowej Kopalni Guido?','["Zabrze", "Tychy", "Będzin", "Żywiec"]'::jsonb,0),
('SL_10','SL','Jaki produkt kojarzy się z tradycyjną kuchnią śląską?','["Kluski śląskie", "Oscypek", "Kartacz podlaski", "Rogalik marciński"]'::jsonb,0),
('MA_01','MA','Jakie miasto jest stolicą województwa małopolskiego?','["Kraków", "Tarnów", "Nowy Sącz", "Zakopane"]'::jsonb,0),
('MA_02','MA','Która słynna budowla znajduje się na wzgórzu nad Wisłą w Krakowie?','["Zamek Królewski na Wawelu", "Zamek Książ", "Zamek w Malborku", "Zamek Czocha"]'::jsonb,0),
('MA_03','MA','Które pasmo górskie leży na południu Małopolski?','["Tatry", "Sudety", "Góry Świętokrzyskie", "Pojezierze Mazurskie"]'::jsonb,0),
('MA_04','MA','Przez Kraków przepływa:','["Wisła", "Odra", "Warta", "Bug"]'::jsonb,0),
('MA_05','MA','Jak nazywa się słynna kopalnia soli pod Krakowem?','["Kopalnia Soli Wieliczka", "Kopalnia Guido", "Kopalnia Srebra", "Kopalnia Turów"]'::jsonb,0),
('MA_06','MA','Które miasto jest zimową stolicą Polski?','["Zakopane", "Tarnów", "Oświęcim", "Bochnia"]'::jsonb,0),
('MA_07','MA','Jak nazywa się rzeka przepływająca przez Tarnów?','["Biała", "Odra", "Narew", "Noteć"]'::jsonb,0),
('MA_08','MA','Który park narodowy słynie z Pienińskiego Przełomu Dunajca?','["Pieniński Park Narodowy", "Kampinoski Park Narodowy", "Wigierski Park Narodowy", "Poleski Park Narodowy"]'::jsonb,0),
('MA_09','MA','Jak nazywa się górski szczyt i symbol Tatr?','["Giewont", "Śnieżka", "Łysica", "Tarnica"]'::jsonb,0),
('MA_10','MA','Które miasto ma znany renesansowy rynek z ratuszem?','["Kraków", "Olsztyn", "Gorzów Wielkopolski", "Bydgoszcz"]'::jsonb,0),
('PK_01','PK','Jakie miasto jest stolicą województwa podkarpackiego?','["Rzeszów", "Przemyśl", "Krosno", "Tarnobrzeg"]'::jsonb,0),
('PK_02','PK','Które góry znajdują się w południowej części regionu?','["Bieszczady", "Tatry", "Karkonosze", "Góry Stołowe"]'::jsonb,0),
('PK_03','PK','Jaka rzeka przepływa przez Przemyśl?','["San", "Warta", "Narew", "Pilica"]'::jsonb,0),
('PK_04','PK','Jezioro Solińskie powstało dzięki budowie zapory na rzece:','["Sanie", "Wiśle", "Odrze", "Warcie"]'::jsonb,0),
('PK_05','PK','Jak nazywa się słynny szczyt Bieszczad?','["Tarnica", "Giewont", "Śnieżka", "Łysica"]'::jsonb,0),
('PK_06','PK','Które miasto słynie z zamku i arystokratycznej rezydencji Łańcut?','["Łańcut", "Rzeszów", "Krosno", "Sanok"]'::jsonb,0),
('PK_07','PK','Jak nazywa się kraina historyczna kojarzona z południowo-wschodnią częścią regionu?','["Bieszczady i Pogórze", "Kaszuby", "Żuławy", "Warmia"]'::jsonb,0),
('PK_08','PK','Które miasto słynie z Muzeum Budownictwa Ludowego i cerkwi z okolic regionu?','["Sanok", "Tarnobrzeg", "Mielec", "Dębica"]'::jsonb,0),
('PK_09','PK','Który park narodowy leży w województwie podkarpackim?','["Bieszczadzki Park Narodowy", "Woliński Park Narodowy", "Kampinoski Park Narodowy", "Słowiński Park Narodowy"]'::jsonb,0),
('PK_10','PK','Z czego słynie Krosno?','["Szkła", "Budowy statków", "Wydobycia bursztynu z Bałtyku", "Produkcji oscypków"]'::jsonb,0),
('SPECIAL_CAPITALS_01','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa mazowieckiego?','["Warszawa", "Radom", "Płock", "Siedlce"]'::jsonb,0),
('SPECIAL_CAPITALS_02','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa małopolskiego?','["Kraków", "Tarnów", "Nowy Sącz", "Zakopane"]'::jsonb,0),
('SPECIAL_CAPITALS_03','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa pomorskiego?','["Gdańsk", "Gdynia", "Sopot", "Słupsk"]'::jsonb,0),
('SPECIAL_CAPITALS_04','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa śląskiego?','["Katowice", "Gliwice", "Częstochowa", "Bielsko-Biała"]'::jsonb,0),
('SPECIAL_CAPITALS_05','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa podlaskiego?','["Białystok", "Suwałki", "Łomża", "Augustów"]'::jsonb,0),
('SPECIAL_CAPITALS_06','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa warmińsko-mazurskiego?','["Olsztyn", "Elbląg", "Ełk", "Iława"]'::jsonb,0),
('SPECIAL_CAPITALS_07','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa dolnośląskiego?','["Wrocław", "Legnica", "Wałbrzych", "Jelenia Góra"]'::jsonb,0),
('SPECIAL_CAPITALS_08','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa opolskiego?','["Opole", "Nysa", "Brzeg", "Kędzierzyn-Koźle"]'::jsonb,0),
('SPECIAL_CAPITALS_09','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa świętokrzyskiego?','["Kielce", "Sandomierz", "Ostrowiec Świętokrzyski", "Starachowice"]'::jsonb,0),
('SPECIAL_CAPITALS_10','SPECIAL_CAPITALS','Jakie miasto jest stolicą województwa podkarpackiego?','["Rzeszów", "Przemyśl", "Krosno", "Mielec"]'::jsonb,0),
('SPECIAL_RIVERS_01','SPECIAL_RIVERS','Jaka jest najdłuższa rzeka Polski?','["Wisła", "Odra", "Warta", "Bug"]'::jsonb,0),
('SPECIAL_RIVERS_02','SPECIAL_RIVERS','Która rzeka przepływa przez Wrocław?','["Odra", "Wisła", "San", "Narew"]'::jsonb,0),
('SPECIAL_RIVERS_03','SPECIAL_RIVERS','Która rzeka przepływa przez Warszawę?','["Wisła", "Odra", "Warta", "Noteć"]'::jsonb,0),
('SPECIAL_RIVERS_04','SPECIAL_RIVERS','Która rzeka przepływa przez Poznań?','["Warta", "Wisła", "Nysa Łużycka", "San"]'::jsonb,0),
('SPECIAL_RIVERS_05','SPECIAL_RIVERS','Która rzeka jest prawym dopływem Wisły i przepływa przez południowo-wschodnią Polskę?','["San", "Odra", "Warta", "Bóbr"]'::jsonb,0),
('SPECIAL_RIVERS_06','SPECIAL_RIVERS','Która rzeka uchodzi do Bałtyku w rejonie Gdańska?','["Wisła", "Warta", "Pilica", "Narew"]'::jsonb,0),
('SPECIAL_RIVERS_07','SPECIAL_RIVERS','Która rzeka stanowi część zachodniej granicy Polski?','["Odra", "Wisła", "Bug", "Narew"]'::jsonb,0),
('SPECIAL_RIVERS_08','SPECIAL_RIVERS','Która rzeka przepływa przez Kraków?','["Wisła", "Warta", "Odra", "Bug"]'::jsonb,0),
('SPECIAL_RIVERS_09','SPECIAL_RIVERS','Która rzeka jest największym dopływem Odry?','["Warta", "San", "Narew", "Pilica"]'::jsonb,0),
('SPECIAL_RIVERS_10','SPECIAL_RIVERS','Która rzeka przepływa przez Toruń?','["Wisła", "Odra", "Warta", "San"]'::jsonb,0),
('SPECIAL_NEIGHBORS_01','SPECIAL_NEIGHBORS','Z którym państwem Polska graniczy na zachodzie?','["Niemcy", "Litwa", "Ukraina", "Słowacja"]'::jsonb,0),
('SPECIAL_NEIGHBORS_02','SPECIAL_NEIGHBORS','Z którym państwem Polska graniczy na południowym zachodzie?','["Czechy", "Białoruś", "Rosja", "Litwa"]'::jsonb,0),
('SPECIAL_NEIGHBORS_03','SPECIAL_NEIGHBORS','Które państwo leży na południe od Polski i ma stolicę w Bratysławie?','["Słowacja", "Czechy", "Ukraina", "Litwa"]'::jsonb,0),
('SPECIAL_NEIGHBORS_04','SPECIAL_NEIGHBORS','Z którym państwem Polska graniczy na północnym wschodzie?','["Litwa", "Niemcy", "Czechy", "Słowacja"]'::jsonb,0),
('SPECIAL_NEIGHBORS_05','SPECIAL_NEIGHBORS','Z którym państwem Polska graniczy na wschodzie i którego stolicą jest Mińsk?','["Białoruś", "Ukraina", "Litwa", "Rosja"]'::jsonb,0),
('SPECIAL_NEIGHBORS_06','SPECIAL_NEIGHBORS','Które państwo graniczy z Polską na południowym wschodzie?','["Ukraina", "Niemcy", "Czechy", "Litwa"]'::jsonb,0),
('SPECIAL_NEIGHBORS_07','SPECIAL_NEIGHBORS','Z jaką częścią Rosji graniczy Polska?','["Obwodem kaliningradzkim", "Syberią", "Kaukazem", "Obwodem moskiewskim"]'::jsonb,0),
('SPECIAL_NEIGHBORS_08','SPECIAL_NEIGHBORS','Ile państw lądowych graniczy z Polską?','["7", "5", "6", "8"]'::jsonb,0),
('SPECIAL_NEIGHBORS_09','SPECIAL_NEIGHBORS','Który sąsiad Polski ma stolicę w Pradze?','["Czechy", "Słowacja", "Litwa", "Białoruś"]'::jsonb,0),
('SPECIAL_NEIGHBORS_10','SPECIAL_NEIGHBORS','Który sąsiad Polski ma stolicę w Wilnie?','["Litwa", "Ukraina", "Niemcy", "Słowacja"]'::jsonb,0),
('SPECIAL_FLAGS_01','SPECIAL_FLAGS','Jakie barwy ma flaga Polski?','["Biała i czerwona", "Niebieska i biała", "Czerwona i żółta", "Biała i zielona"]'::jsonb,0),
('SPECIAL_FLAGS_02','SPECIAL_FLAGS','Która flaga składa się z poziomych pasów: czarnego, czerwonego i złotego?','["Niemiec", "Polski", "Czech", "Litwy"]'::jsonb,0),
('SPECIAL_FLAGS_03','SPECIAL_FLAGS','Która flaga ma biało-czerwone pasy i niebieski trójkąt przy maszcie?','["Czech", "Słowacji", "Ukrainy", "Litwy"]'::jsonb,0),
('SPECIAL_FLAGS_04','SPECIAL_FLAGS','Która flaga ma trzy poziome pasy: biały, niebieski i czerwony?','["Rosji", "Niemiec", "Ukrainy", "Polski"]'::jsonb,0),
('SPECIAL_FLAGS_05','SPECIAL_FLAGS','Która flaga ma dwa poziome pasy: niebieski nad żółtym?','["Ukrainy", "Litwy", "Białorusi", "Niemiec"]'::jsonb,0),
('SPECIAL_FLAGS_06','SPECIAL_FLAGS','Która flaga ma trzy poziome pasy: żółty, zielony i czerwony?','["Litwy", "Polski", "Rosji", "Czech"]'::jsonb,0),
('SPECIAL_FLAGS_07','SPECIAL_FLAGS','Która flaga ma czerwony i zielony pas oraz biało-czerwony ornament przy maszcie?','["Białorusi", "Ukrainy", "Litwy", "Niemiec"]'::jsonb,0),
('SPECIAL_FLAGS_08','SPECIAL_FLAGS','Na której fladze występują biały i czerwony kolor, podobnie jak na fladze Polski, ale z dodatkowym niebieskim elementem?','["Czech", "Niemiec", "Litwy", "Ukrainy"]'::jsonb,0),
('SPECIAL_FLAGS_09','SPECIAL_FLAGS','Który kolor znajduje się na górze flagi Polski?','["Biały", "Czerwony", "Niebieski", "Zielony"]'::jsonb,0),
('SPECIAL_FLAGS_10','SPECIAL_FLAGS','Który kolor znajduje się na dole flagi Polski?','["Czerwony", "Biały", "Żółty", "Niebieski"]'::jsonb,0),
('SPECIAL_LANDMARKS_01','SPECIAL_LANDMARKS','W jakim mieście znajduje się Zamek Królewski na Wawelu?','["Kraków", "Warszawa", "Gdańsk", "Poznań"]'::jsonb,0),
('SPECIAL_LANDMARKS_02','SPECIAL_LANDMARKS','W jakim mieście znajduje się Zamek Krzyżacki wpisany na listę UNESCO?','["Malbork", "Toruń", "Gniezno", "Lublin"]'::jsonb,0),
('SPECIAL_LANDMARKS_03','SPECIAL_LANDMARKS','W jakim mieście znajduje się Pałac Kultury i Nauki?','["Warszawa", "Łódź", "Katowice", "Wrocław"]'::jsonb,0),
('SPECIAL_LANDMARKS_04','SPECIAL_LANDMARKS','Z jakim miastem kojarzy się zabytkowy Żuraw nad Motławą?','["Gdańsk", "Szczecin", "Gdynia", "Elbląg"]'::jsonb,0),
('SPECIAL_LANDMARKS_05','SPECIAL_LANDMARKS','W jakim mieście znajduje się Hala Stulecia?','["Wrocław", "Opole", "Poznań", "Kraków"]'::jsonb,0),
('SPECIAL_LANDMARKS_06','SPECIAL_LANDMARKS','W jakim mieście znajduje się Jasna Góra?','["Częstochowa", "Kielce", "Radom", "Rzeszów"]'::jsonb,0),
('SPECIAL_LANDMARKS_07','SPECIAL_LANDMARKS','W jakim mieście znajduje się słynny rynek z ratuszem i koziołkami?','["Poznań", "Lublin", "Toruń", "Białystok"]'::jsonb,0),
('SPECIAL_LANDMARKS_08','SPECIAL_LANDMARKS','W jakim mieście znajduje się Zamek Książąt Pomorskich?','["Szczecin", "Gdańsk", "Warszawa", "Opole"]'::jsonb,0),
('SPECIAL_LANDMARKS_09','SPECIAL_LANDMARKS','Które miasto słynie z gotyckiej starówki i związku z Mikołajem Kopernikiem?','["Toruń", "Łódź", "Kielce", "Rzeszów"]'::jsonb,0),
('SPECIAL_LANDMARKS_10','SPECIAL_LANDMARKS','W jakim mieście znajduje się Sukiennice?','["Kraków", "Warszawa", "Wrocław", "Lublin"]'::jsonb,0)
on conflict(id) do update set quiz_code=excluded.quiz_code,question=excluded.question,options=excluded.options,correct_index=excluded.correct_index;

create or replace function public.start_secure_quiz(p_quiz_code text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_ids jsonb; v_questions jsonb; v_session uuid; v_banned boolean;
begin
 if v_uid is null then raise exception 'Not authenticated'; end if;
 select coalesce(banned,false) into v_banned from public.profiles where id=v_uid;
 if v_banned then raise exception 'Account banned'; end if;

 if p_quiz_code='SPECIAL_RANDOM' then
   select jsonb_agg(id),jsonb_agg(jsonb_build_object('id',id,'q',question,'a',options))
   into v_ids,v_questions from(
     select id,question,options from public.quiz_questions
     where quiz_code in('ZP','PM','WN','PD','LB','KP','WP','MZ','LD','LU','DS','OP','SK','SL','MA','PK')
     order by random() limit 10
   )q;
 else
   select jsonb_agg(id),jsonb_agg(jsonb_build_object('id',id,'q',question,'a',options))
   into v_ids,v_questions from(
     select id,question,options from public.quiz_questions where quiz_code=p_quiz_code order by random() limit 10
   )q;
 end if;

 if v_ids is null or jsonb_array_length(v_ids)<>10 then raise exception 'Quiz unavailable'; end if;
 insert into public.quiz_sessions(user_id,quiz_code,question_ids) values(v_uid,p_quiz_code,v_ids) returning id into v_session;
 return jsonb_build_object('session_id',v_session,'questions',v_questions);
end;$$;
revoke all on function public.start_secure_quiz(text) from public,anon;
grant execute on function public.start_secure_quiz(text) to authenticated;

create or replace function public.submit_secure_answer(p_session_id uuid,p_question_index integer,p_answer_index integer)
returns table(correct boolean,correct_index integer)
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_session public.quiz_sessions%rowtype; v_qid text; v_key text:=p_question_index::text;
begin
 if v_uid is null then raise exception 'Not authenticated'; end if;
 if p_question_index<0 or p_question_index>9 or p_answer_index<0 or p_answer_index>3 then raise exception 'Invalid answer'; end if;
 select * into v_session from public.quiz_sessions where id=p_session_id and user_id=v_uid for update;
 if not found or v_session.completed then raise exception 'Invalid quiz session'; end if;
 if v_session.answers ? v_key then raise exception 'Question already answered'; end if;
 v_qid:=v_session.question_ids->>p_question_index;
 select q.correct_index into correct_index from public.quiz_questions q where q.id=v_qid;
 if correct_index is null then raise exception 'Question unavailable'; end if;
 correct:=p_answer_index=correct_index;
 update public.quiz_sessions set answers=jsonb_set(answers,array[v_key],to_jsonb(correct),true) where id=p_session_id;
 return next;
end;$$;
revoke all on function public.submit_secure_answer(uuid,integer,integer) from public,anon;
grant execute on function public.submit_secure_answer(uuid,integer,integer) to authenticated;

create or replace function public.finalize_secure_quiz(p_session_id uuid)
returns table(score integer,xp_awarded integer,total_xp integer,weekly_xp integer,league text,week_key date,region_passed boolean,already_rewarded boolean)
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_session public.quiz_sessions%rowtype; v_week date:=current_date-((extract(isodow from current_date)::int)-1); v_reward integer; v_exists boolean; v_is_region boolean;
begin
 if v_uid is null then raise exception 'Not authenticated'; end if;
 select * into v_session from public.quiz_sessions where id=p_session_id and user_id=v_uid for update;
 if not found then raise exception 'Invalid quiz session'; end if;
 select count(*)::integer into score from jsonb_each_text(v_session.answers)x where x.value='true';
 if jsonb_object_length(v_session.answers)<>10 then raise exception 'Quiz not complete'; end if;
 v_is_region:=v_session.quiz_code in('ZP','PM','WN','PD','LB','KP','WP','MZ','LD','LU','DS','OP','SK','SL','MA','PK');
 region_passed:=v_is_region and score>=5;
 insert into public.progress(user_id) values(v_uid) on conflict(user_id) do nothing;
 select exists(select 1 from public.quiz_rewards where user_id=v_uid and region_code=v_session.quiz_code and reward_day=current_date) into v_exists;
 if v_exists then xp_awarded:=0;already_rewarded:=true;
 else
   v_reward:=(score*10)+case when score>=5 then(case when v_is_region then 25 else 20 end)else 0 end;
   xp_awarded:=v_reward;already_rewarded:=false;
   update public.progress p set xp=coalesce(p.xp,0)+v_reward,
     weekly_xp=case when p.week_key is distinct from v_week then v_reward else coalesce(p.weekly_xp,0)+v_reward end,
     week_key=v_week,
     passed_regions=case when region_passed then jsonb_set(coalesce(p.passed_regions,'{}'::jsonb),array[v_session.quiz_code],'true'::jsonb,true) else coalesce(p.passed_regions,'{}'::jsonb) end,
     updated_at=now() where p.user_id=v_uid;
   update public.progress p set league=case when p.weekly_xp>=1200 then 'gold' when p.weekly_xp>=500 then 'silver' else 'bronze' end where p.user_id=v_uid;
   insert into public.quiz_rewards(user_id,region_code,reward_day,score,xp_awarded) values(v_uid,v_session.quiz_code,current_date,score,v_reward);
 end if;
 update public.quiz_sessions set completed=true where id=p_session_id;
 select p.xp,p.weekly_xp,p.league,p.week_key into total_xp,weekly_xp,league,week_key from public.progress p where p.user_id=v_uid;
 insert into public.league_entries(user_id,display_name,weekly_xp,league,week_key,updated_at)
 select v_uid,coalesce(pr.display_name,split_part(u.email,'@',1),'gracz'),weekly_xp,league,week_key,now()
 from auth.users u left join public.profiles pr on pr.id=u.id where u.id=v_uid
 on conflict(user_id) do update set display_name=excluded.display_name,weekly_xp=excluded.weekly_xp,league=excluded.league,week_key=excluded.week_key,updated_at=now();
 return next;
end;$$;
revoke all on function public.finalize_secure_quiz(uuid) from public,anon;
grant execute on function public.finalize_secure_quiz(uuid) to authenticated;
