-- POLSKIFY — SECURE XP PATCH
-- Uruchom w Supabase -> SQL Editor -> New query -> Run
-- Ten patch:
-- 1) blokuje zwykłemu użytkownikowi bezpośrednie UPDATE XP / ligi / zaliczonych regionów,
-- 2) nalicza XP przez funkcję SECURITY DEFINER,
-- 3) pozwala zdobyć XP za dany region maksymalnie raz dziennie,
-- 4) zachowuje panel admina przez osobną chronioną funkcję.

create table if not exists public.quiz_rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  region_code text not null,
  reward_day date not null default current_date,
  score integer not null check (score between 0 and 10),
  xp_awarded integer not null check (xp_awarded between 0 and 125),
  created_at timestamptz not null default now(),
  unique(user_id, region_code, reward_day)
);

alter table public.quiz_rewards enable row level security;

revoke all on table public.quiz_rewards from anon, authenticated;
grant select on table public.quiz_rewards to authenticated;

drop policy if exists "quiz_rewards_select_own" on public.quiz_rewards;
create policy "quiz_rewards_select_own"
on public.quiz_rewards for select
to authenticated
using ((select auth.uid()) = user_id);

-- Odbieramy bezpośrednią możliwość modyfikowania chronionych pól.
revoke insert, update on table public.progress from authenticated;
grant insert(user_id) on table public.progress to authenticated;
grant update(stats, streak_count, streak_best, streak_last_day, active_days, updated_at)
on table public.progress to authenticated;

revoke insert, update on table public.league_entries from authenticated;
grant select on table public.league_entries to authenticated;

create or replace function public.award_quiz_xp(
  p_region_code text,
  p_score integer,
  p_total integer
)
returns table(
  xp_awarded integer,
  total_xp integer,
  weekly_xp integer,
  league text,
  week_key date,
  region_passed boolean,
  already_rewarded boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_reward integer;
  v_week date := current_date - ((extract(isodow from current_date)::int) - 1);
  v_exists boolean;
  v_weekly integer;
  v_total integer;
  v_league text;
  v_pass boolean;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if p_region_code not in ('ZP','PM','WN','PD','LB','KP','WP','MZ','LD','LU','DS','OP','SK','SL','MA','PK') then
    raise exception 'Invalid region';
  end if;

  if p_total <> 10 or p_score < 0 or p_score > 10 then
    raise exception 'Invalid quiz result';
  end if;

  insert into public.progress(user_id)
  values (v_uid)
  on conflict (user_id) do nothing;

  select exists(
    select 1 from public.quiz_rewards
    where user_id = v_uid
      and region_code = p_region_code
      and reward_day = current_date
  ) into v_exists;

  v_pass := p_score >= 5;

  if v_exists then
    select p.xp, p.weekly_xp, p.league, p.week_key
    into v_total, v_weekly, v_league, week_key
    from public.progress p where p.user_id = v_uid;

    xp_awarded := 0;
    total_xp := coalesce(v_total,0);
    weekly_xp := coalesce(v_weekly,0);
    league := coalesce(v_league,'bronze');
    region_passed := v_pass;
    already_rewarded := true;
    return next;
    return;
  end if;

  v_reward := (p_score * 10) + case when v_pass then 25 else 0 end;

  update public.progress p
  set
    xp = coalesce(p.xp,0) + v_reward,
    weekly_xp = case
      when p.week_key is distinct from v_week then v_reward
      else coalesce(p.weekly_xp,0) + v_reward
    end,
    week_key = v_week,
    passed_regions = case
      when v_pass then jsonb_set(coalesce(p.passed_regions,'{}'::jsonb), array[p_region_code], 'true'::jsonb, true)
      else coalesce(p.passed_regions,'{}'::jsonb)
    end,
    updated_at = now()
  where p.user_id = v_uid;

  update public.progress p
  set league = case
      when p.weekly_xp >= 1200 then 'gold'
      when p.weekly_xp >= 500 then 'silver'
      else 'bronze'
    end
  where p.user_id = v_uid;

  insert into public.quiz_rewards(user_id, region_code, reward_day, score, xp_awarded)
  values (v_uid, p_region_code, current_date, p_score, v_reward);

  select p.xp, p.weekly_xp, p.league, p.week_key
  into v_total, v_weekly, v_league, week_key
  from public.progress p where p.user_id = v_uid;

  insert into public.league_entries(user_id, display_name, weekly_xp, league, week_key, updated_at)
  select
    v_uid,
    coalesce(pr.display_name, split_part(u.email,'@',1), 'gracz'),
    v_weekly,
    v_league,
    v_week,
    now()
  from auth.users u
  left join public.profiles pr on pr.id = u.id
  where u.id = v_uid
  on conflict(user_id) do update set
    display_name = excluded.display_name,
    weekly_xp = excluded.weekly_xp,
    league = excluded.league,
    week_key = excluded.week_key,
    updated_at = now();

  xp_awarded := v_reward;
  total_xp := v_total;
  weekly_xp := v_weekly;
  league := v_league;
  region_passed := v_pass;
  already_rewarded := false;
  return next;
end;
$$;

revoke all on function public.award_quiz_xp(text,integer,integer) from public, anon;
grant execute on function public.award_quiz_xp(text,integer,integer) to authenticated;

create or replace function public.admin_set_own_progress(
  p_xp integer default null,
  p_weekly_xp integer default null,
  p_passed_regions jsonb default null
)
returns table(
  total_xp integer,
  weekly_xp integer,
  league text,
  week_key date
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_is_admin boolean;
  v_week date := current_date - ((extract(isodow from current_date)::int) - 1);
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;

  select is_admin into v_is_admin from public.profiles where id = v_uid;
  if coalesce(v_is_admin,false) = false then
    raise exception 'Admin only';
  end if;

  insert into public.progress(user_id)
  values (v_uid)
  on conflict(user_id) do nothing;

  update public.progress p
  set
    xp = case when p_xp is null then p.xp else greatest(0,p_xp) end,
    weekly_xp = case when p_weekly_xp is null then p.weekly_xp else greatest(0,p_weekly_xp) end,
    week_key = case when p_weekly_xp is null then p.week_key else v_week end,
    passed_regions = case when p_passed_regions is null then p.passed_regions else p_passed_regions end,
    updated_at = now()
  where p.user_id = v_uid;

  update public.progress p
  set league = case
      when p.weekly_xp >= 1200 then 'gold'
      when p.weekly_xp >= 500 then 'silver'
      else 'bronze'
    end
  where p.user_id = v_uid;

  select p.xp, p.weekly_xp, p.league, p.week_key
  into total_xp, weekly_xp, league, week_key
  from public.progress p
  where p.user_id = v_uid;

  insert into public.league_entries(user_id, display_name, weekly_xp, league, week_key, updated_at)
  select
    v_uid,
    coalesce(pr.display_name, split_part(u.email,'@',1), 'gracz'),
    weekly_xp,
    league,
    week_key,
    now()
  from auth.users u
  left join public.profiles pr on pr.id = u.id
  where u.id = v_uid
  on conflict(user_id) do update set
    display_name = excluded.display_name,
    weekly_xp = excluded.weekly_xp,
    league = excluded.league,
    week_key = excluded.week_key,
    updated_at = now();

  return next;
end;
$$;

revoke all on function public.admin_set_own_progress(integer,integer,jsonb) from public, anon;
grant execute on function public.admin_set_own_progress(integer,integer,jsonb) to authenticated;
